apiVersion: apps/v1
kind: Deployment
metadata:
  name: kombat-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kombat-app
  template:
    metadata:
      labels:
        app: kombat-app
    spec:
      containers:
      - name: kombat
        image: thebadsoftwareclub/kombat
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
          hostPort: 80

