apiVersion: apps/v1
kind: Deployment
metadata:
  name: goof
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goof-label
  template:
    metadata:
      labels:
        app: goof-label
    spec:
      containers:
      - name: goof
        image: thebadsoftwareclub/goof
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        securityContext:
          capabilities:
            add: [ "CAP_SYS_ADMIN" ]

---
apiVersion: v1
kind: Service
metadata:
  name: goofservice
  labels:
    app: goof
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: goof-label
  type: LoadBalancer

