version: '3.3'

services:
  app:
    build: ./server
    expose:
      - 3000
    ports:
      - '80:3000'
    volumes:
      - ./game:/usr/src/app/game
    command: npm run start
    stdin_open: true
    tty: true